// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XyloType.Infrastructure.DbContexts;

#nullable disable

namespace XyloType.Infrastructure.Migrations;

[DbContext(typeof(DactyloDbContext))]
[Migration("20261001075311_AddImportedSourcesAndWordExclusion")]
partial class _20261001075311_AddImportedSourcesAndWordExclusion
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118");

        modelBuilder.Entity("XyloType.Domain.Entities.ImportedSource", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ContentHash")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("TEXT");

                b.Property<int>("IgnoredWords")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("ImportedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("LanguageCode")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("TEXT");

                b.Property<int>("NewWords")
                    .HasColumnType("INTEGER");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("TEXT");

                b.Property<int>("UpdatedWords")
                    .HasColumnType("INTEGER");

                b.Property<int>("WordsRead")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("ContentHash");

                b.ToTable("ImportedSources");
            });

        modelBuilder.Entity("XyloType.Domain.Entities.Word", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsExcluded")
                    .HasColumnType("INTEGER");

                b.Property<string>("LanguageCode")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("TEXT");

                b.Property<int>("Length")
                    .HasColumnType("INTEGER");

                b.Property<int>("OccurrenceCount")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(1);

                b.Property<string>("Text")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("IsExcluded");

                b.HasIndex("LanguageCode");

                b.HasIndex("Length");

                b.HasIndex("OccurrenceCount");

                b.HasIndex("Text", "LanguageCode")
                    .IsUnique();

                b.ToTable("Words");
            });

        modelBuilder.Entity("XyloType.Domain.Entities.WordAnalysis", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("ExternalAccent")
                    .HasColumnType("INTEGER");

                b.Property<int>("FingerMask")
                    .HasColumnType("INTEGER");

                b.Property<int>("Layout")
                    .HasColumnType("INTEGER");

                b.Property<int>("RowMask")
                    .HasColumnType("INTEGER");

                b.Property<bool>("UsesLeftHand")
                    .HasColumnType("INTEGER");

                b.Property<bool>("UsesRightHand")
                    .HasColumnType("INTEGER");

                b.Property<int>("WordId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("Layout");

                b.HasIndex("WordId");

                b.HasIndex("Layout", "FingerMask");

                b.HasIndex("Layout", "RowMask");

                b.HasIndex("WordId", "Layout")
                    .IsUnique();

                b.HasIndex("Layout", "UsesLeftHand", "UsesRightHand");

                b.ToTable("WordAnalyses");
            });

        modelBuilder.Entity("XyloType.Domain.Entities.WordAnalysis", b =>
            {
                b.HasOne("XyloType.Domain.Entities.Word", "Word")
                    .WithMany("Analyses")
                    .HasForeignKey("WordId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Word");
            });

        modelBuilder.Entity("XyloType.Domain.Entities.Word", b =>
            {
                b.Navigation("Analyses");
            });
#pragma warning restore 612, 618
    }
}
