// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XyloType.Infrastructure.DbContexts;

#nullable disable

namespace XyloType.Infrastructure.Migrations;

[DbContext(typeof(DactyloDbContext))]
partial class DactyloDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20261009090757_AddUsersAndExerciseAttempts";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118");

        modelBuilder.Entity("XyloType.Domain.Entities.ExerciseAttempt", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<double>("Accuracy")
                    .HasColumnType("REAL");

                b.Property<int>("Characters")
                    .HasColumnType("INTEGER");

                b.Property<int>("CharactersWithError")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CompletedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<double>("DurationSeconds")
                    .HasColumnType("REAL");

                b.Property<Guid>("ExerciseId")
                    .HasColumnType("TEXT");

                b.Property<double>("Score")
                    .HasColumnType("REAL");

                b.Property<int>("UserId")
                    .HasColumnType("INTEGER");

                b.Property<double>("WordsPerMinute")
                    .HasColumnType("REAL");

                b.Property<int>("WrongKeyPresses")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("UserId", "ExerciseId");

                b.ToTable("ExerciseAttempts");
            });

        modelBuilder.Entity("XyloType.Domain.Entities.ImportedSource", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ContentHash")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("TEXT");

                b.Property<int>("IgnoredWords")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("ImportedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("LanguageCode")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("TEXT");

                b.Property<int>("NewWords")
                    .HasColumnType("INTEGER");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("TEXT");

                b.Property<int>("UpdatedWords")
                    .HasColumnType("INTEGER");

                b.Property<int>("WordsRead")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("ContentHash");

                b.ToTable("ImportedSources");
            });

        modelBuilder.Entity("XyloType.Domain.Entities.UserProfile", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(40)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Users");
            });

        modelBuilder.Entity("XyloType.Domain.Entities.Word", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsExcluded")
                    .HasColumnType("INTEGER");

                b.Property<string>("LanguageCode")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("TEXT");

                b.Property<int>("Length")
                    .HasColumnType("INTEGER");

                b.Property<int>("OccurrenceCount")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(1);

                b.Property<string>("Text")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("IsExcluded");

                b.HasIndex("LanguageCode");

                b.HasIndex("Length");

                b.HasIndex("OccurrenceCount");

                b.HasIndex("Text", "LanguageCode")
                    .IsUnique();

                b.ToTable("Words");
            });

        modelBuilder.Entity("XyloType.Domain.Entities.WordAnalysis", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("ExternalAccent")
                    .HasColumnType("INTEGER");

                b.Property<int>("FingerMask")
                    .HasColumnType("INTEGER");

                b.Property<int>("Layout")
                    .HasColumnType("INTEGER");

                b.Property<int>("RowMask")
                    .HasColumnType("INTEGER");

                b.Property<bool>("UsesLeftHand")
                    .HasColumnType("INTEGER");

                b.Property<bool>("UsesRightHand")
                    .HasColumnType("INTEGER");

                b.Property<int>("WordId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("Layout");

                b.HasIndex("WordId");

                b.HasIndex("Layout", "FingerMask");

                b.HasIndex("Layout", "RowMask");

                b.HasIndex("WordId", "Layout")
                    .IsUnique();

                b.HasIndex("Layout", "UsesLeftHand", "UsesRightHand");

                b.ToTable("WordAnalyses");
            });

        modelBuilder.Entity("XyloType.Domain.Entities.ExerciseAttempt", b =>
            {
                b.HasOne("XyloType.Domain.Entities.UserProfile", "User")
                    .WithMany("Attempts")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("XyloType.Domain.Entities.WordAnalysis", b =>
            {
                b.HasOne("XyloType.Domain.Entities.Word", "Word")
                    .WithMany("Analyses")
                    .HasForeignKey("WordId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Word");
            });

        modelBuilder.Entity("XyloType.Domain.Entities.UserProfile", b =>
            {
                b.Navigation("Attempts");
            });

        modelBuilder.Entity("XyloType.Domain.Entities.Word", b =>
            {
                b.Navigation("Analyses");
            });
#pragma warning restore 612, 618
    }
}
